
<#
#̷𝓍   𝓐𝓡𝓢 𝓢𝓒𝓡𝓘𝓟𝓣𝓤𝓜
#̷𝓍   🇵​​​​​🇴​​​​​🇼​​​​​🇪​​​​​🇷​​​​​🇸​​​​​🇭​​​​​🇪​​​​​🇱​​​​​🇱​​​​​ 🇸​​​​​🇨​​​​​🇷​​​​​🇮​​​​​🇵​​​​​🇹​​​​​ 🇧​​​​​🇾​​​​​ 🇬​​​​​🇺​​​​​🇮​​​​​🇱​​​​​🇱​​​​​🇦​​​​​🇺​​​​​🇲​​​​​🇪​​​​​🇵​​​​​🇱​​​​​🇦​​​​​🇳​​​​​🇹​​​​​🇪​​​​​.🇶​​​​​🇨​​​​​@🇬​​​​​🇲​​​​​🇦​​​​​🇮​​​​​🇱​​​​​.🇨​​​​​🇴​​​​​🇲​​​​​
#̷𝓍   
#̷𝓍   PowerShell GitHub Module
#>



function Invoke-InstallGhClient {
    [CmdletBinding(SupportsShouldProcess)]
    param (
        [Parameter(Mandatory=$false)]
        [Alias('t', 'type')]
        [ValidateSet('WinGet', 'Choco', 'Package','DelWinGet','DelChoco')]
        [string]$InstallType='Package'
        )



    $DelChoco = "CgAgACAAIAAgACAAIAAgACAAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBDAGgAbwBjAG8ARQB4AGUAUABhAHQAaAB7ACAAIAAgAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBDAG0AZABsAGUAdABCAGkAbgBkAGkAbgBnACgAUwB1AHAAcABvAHIAdABzAFMAaABvAHUAbABkAFAAcgBvAGMAZQBzAHMAKQBdAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcABhAHIAYQBtACgAKQAKAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABjAGgAbwBjAG8AQwBtAGQAIAA9ACAARwBlAHQALQBDAG8AbQBtAGEAbgBkACAAJwBjAGgAbwBjAG8ALgBlAHgAZQAnACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABJAGcAbgBvAHIAZQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAoACgAJABjAGgAbwBjAG8AQwBtAGQAIAAtAG4AZQAgACQATgB1AGwAbAAgACkAIAAtAEEAbgBkACAAKAB0AGUAcwB0AC0AcABhAHQAaAAgAC0AUABhAHQAaAAgACcAJAAoACQAYwBoAG8AYwBvAEMAbQBkAC4AUwBvAHUAcgBjAGUAKQAnACAALQBQAGEAdABoAFQAeQBwAGUAIABMAGUAYQBmACkAKQB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGMAaABvAGMAbwBBAHAAcAAgAD0AIAAkAGMAaABvAGMAbwBDAG0AZAAuAFMAbwB1AHIAYwBlAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBWAGUAcgBiAG8AcwBlACAAJwAFJyAARgBvAHUAbgBkACAAYwBoAG8AYwBvAC4AZQB4AGUAIABDAE0ARAAgAFsAJABjAGgAbwBjAG8AQQBwAHAAXQAnAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABSAGUAdAB1AHIAbgAgACQAYwBoAG8AYwBvAEEAcABwACAACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgAAoACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGMAaABvAGMAbwBBAHAAcAAgAD0AIAAiACQARQBOAFYAOgBQAHIAbwBnAHIAYQBtAEQAYQB0AGEAXABjAGgAbwBjAG8AbABhAHQAZQB5AFwAYgBpAG4AIgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBoAG8AYwBvAEEAcABwACAAPQAgAEoAbwBpAG4ALQBQAGEAdABoACAAJABjAGgAbwBjAG8AQQBwAHAAIAAnAGMAaABvAGMAbwAuAGUAeABlACcACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAKAB0AGUAcwB0AC0AcABhAHQAaAAgACQAYwBoAG8AYwBvAEEAcABwACkAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAAkAGMAaABvAGMAbwBBAHAAcAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABUAGgAcgBvAHcAIAAnAEMAbwB1AGwAZAAgAG4AbwB0ACAAbABvAGMAYQB0AGUAIABjAGgAbwBjAG8ALgBlAHgAZQAnAAoAIAAgACAAIAAgACAAIAAgAH0ACgAKACAAIAAgACAAIAAgACAAIAAkAEMAaABvAGMAbwBFAHgAZQBQAGEAdABoACAAPQAgAEcAZQB0AC0AQwBoAG8AYwBvAEUAeABlAFAAYQB0AGgACgAKACAAIAAgACAAIAAgACAAIAAmACIAJABDAGgAbwBjAG8ARQB4AGUAUABhAHQAaAAiACAAJwB1AG4AaQBuAHMAdABhAGwAbAAnACAAJwBnAGgAJwAKAAoAIAAgACAAIAAgACAAIAAgAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgADUA"
    $DelWinGet = "CgAgACAAIAAgACAAIAAgACAAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBXAGkAbgBHAGUAdABFAHgAZQBQAGEAdABoAHsAIAAgACAACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABbAEMAbQBkAGwAZQB0AEIAaQBuAGQAaQBuAGcAKABTAHUAcABwAG8AcgB0AHMAUwBoAG8AdQBsAGQAUAByAG8AYwBlAHMAcwApAF0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABwAGEAcgBhAG0AKAApAAoACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHcAaQBuAGcAZQB0AEMAbQBkACAAPQAgAEcAZQB0AC0AQwBvAG0AbQBhAG4AZAAgACcAdwBpAG4AZwBlAHQALgBlAHgAZQAnACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABJAGcAbgBvAHIAZQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAoACgAJAB3AGkAbgBnAGUAdABDAG0AZAAgAC0AbgBlACAAJABOAHUAbABsACAAKQAgAC0AQQBuAGQAIAAoAHQAZQBzAHQALQBwAGEAdABoACAALQBQAGEAdABoACAAJwAkACgAJAB3AGkAbgBnAGUAdABDAG0AZAAuAFMAbwB1AHIAYwBlACkAJwAgAC0AUABhAHQAaABUAHkAcABlACAATABlAGEAZgApACkAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAB3AGkAbgBnAGUAdABBAHAAcAAgAD0AIAAkAHcAaQBuAGcAZQB0AEMAbQBkAC4AUwBvAHUAcgBjAGUACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAFYAZQByAGIAbwBzAGUAIAAnAAUnIABGAG8AdQBuAGQAIAB3AGkAbgBnAGUAdAAuAGUAeABlACAAQwBNAEQAIABbACQAdwBpAG4AZwBlAHQAQQBwAHAAXQAnAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABSAGUAdAB1AHIAbgAgACQAdwBpAG4AZwBlAHQAQQBwAHAAIAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAACgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAdwBpAG4AZwBlAHQAQQBwAHAAIAA9ACAAKABSAGUAcwBvAGwAdgBlAC0AUABhAHQAaAAgACIAJABFAE4AVgA6AEEAUABQAEQAQQBUAEEAXAAuAC4AXABMAG8AYwBhAGwAXABNAGkAYwByAG8AcwBvAGYAdABcAFcAaQBuAGQAbwB3AHMAQQBwAHAAcwAiACkALgBQAGEAdABoAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAB3AGkAbgBnAGUAdABBAHAAcAAgAD0AIABKAG8AaQBuAC0AUABhAHQAaAAgACQAdwBpAG4AZwBlAHQAQQBwAHAAIAAnAHcAaQBuAGcAZQB0AC4AZQB4AGUAJwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAoAHQAZQBzAHQALQBwAGEAdABoACAAJAB3AGkAbgBnAGUAdABBAHAAcAApAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJAB3AGkAbgBnAGUAdABBAHAAcAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABUAGgAcgBvAHcAIAAnAEMAbwB1AGwAZAAgAG4AbwB0ACAAbABvAGMAYQB0AGUAIAB3AGkAbgBnAGUAdAAuAGUAeABlACcACgAgACAAIAAgACAAIAAgACAAfQAKAAoAIAAgACAAIAAgACAAIAAgACQAVwBpAG4ARwBlAHQARQB4AGUAUABhAHQAaAAgAD0AIABHAGUAdAAtAFcAaQBuAEcAZQB0AEUAeABlAFAAYQB0AGgACgAKACAAIAAgACAAIAAgACAAIAAmACIAJABXAGkAbgBHAGUAdABFAHgAZQBQAGEAdABoACIAIAAnAHUAbgBpAG4AcwB0AGEAbABsACcAIAAnAC0ALQBpAGQAJwAgACcARwBpAHQASAB1AGIALgBjAGwAaQAnAAoACgAgACAAIAAgACAAIAAgACAAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAANQA="


    $EncodedCommandMSI = "CgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHAAcgBlAHYAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAIAA9ACAAJABnAGwAbwBiAGEAbAA6AFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABnAGwAbwBiAGEAbAA6AFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlACAAPQAgACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAFUAcgBsACAAPQAgACcAaAB0AHQAcABzADoALwAvAGcAaQB0AGgAdQBiAC4AYwBvAG0ALwBjAGwAaQAvAGMAbABpAC8AcgBlAGwAZQBhAHMAZQBzAC8AZABvAHcAbgBsAG8AYQBkAC8AdgAyAC4AMgAwAC4AMgAvAGcAaABfADIALgAyADAALgAyAF8AdwBpAG4AZABvAHcAcwBfAGEAbQBkADYANAAuAG0AcwBpACcACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAEQAZQBzAHQARgBpAGwAZQAgAD0AIAAiACQARQBOAFYAOgBUAGUAbQBwAFwAZwBoAF8AMgAuADIAMAAuADIAXwB3AGkAbgBkAG8AdwBzAF8AYQBtAGQANgA0AC4AbQBzAGkAIgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAEkAbgB2AG8AawBlAC0AVwBlAGIAUgBlAHEAdQBlAHMAdAAgAC0AVQByAGkAIAAkAFUAcgBsACAAIAAtAE8AdQB0AEYAaQBsAGUAIAAkAEQAZQBzAHQARgBpAGwAZQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAZwBsAG8AYgBhAGwAOgBQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAkAHAAcgBlAHYAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUACgAgACAAIAAgACAAIAAgACAAIAAgACAACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAKABUAGUAcwB0AC0AUABhAHQAaAAgACQARABlAHMAdABGAGkAbABlACkAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJgAiACQARABlAHMAdABGAGkAbABlACIAIAAnAC8AcQB1AGkAZQB0ACcAIAAnAC8AcABhAHMAcwBpAHYAZQAnACAAJwAvAG4AbwByAGUAcwB0AGEAcgB0ACcACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AAoACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByAHQALQBTAGwAZQBlAHAAIAA1AA=="
    $EncodedCommandChoco = "CgAgACAAIAAgACAAIAAgACAAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBDAGgAbwBjAG8ARQB4AGUAUABhAHQAaAB7ACAAIAAgAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBDAG0AZABsAGUAdABCAGkAbgBkAGkAbgBnACgAUwB1AHAAcABvAHIAdABzAFMAaABvAHUAbABkAFAAcgBvAGMAZQBzAHMAKQBdAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcABhAHIAYQBtACgAKQAKAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABjAGgAbwBjAG8AQwBtAGQAIAA9ACAARwBlAHQALQBDAG8AbQBtAGEAbgBkACAAJwBjAGgAbwBjAG8ALgBlAHgAZQAnACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABJAGcAbgBvAHIAZQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAoACgAJABjAGgAbwBjAG8AQwBtAGQAIAAtAG4AZQAgACQATgB1AGwAbAAgACkAIAAtAEEAbgBkACAAKAB0AGUAcwB0AC0AcABhAHQAaAAgAC0AUABhAHQAaAAgACcAJAAoACQAYwBoAG8AYwBvAEMAbQBkAC4AUwBvAHUAcgBjAGUAKQAnACAALQBQAGEAdABoAFQAeQBwAGUAIABMAGUAYQBmACkAKQB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGMAaABvAGMAbwBBAHAAcAAgAD0AIAAkAGMAaABvAGMAbwBDAG0AZAAuAFMAbwB1AHIAYwBlAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBWAGUAcgBiAG8AcwBlACAAJwAFJyAARgBvAHUAbgBkACAAYwBoAG8AYwBvAC4AZQB4AGUAIABDAE0ARAAgAFsAJABjAGgAbwBjAG8AQQBwAHAAXQAnAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABSAGUAdAB1AHIAbgAgACQAYwBoAG8AYwBvAEEAcABwACAACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgAAoACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGMAaABvAGMAbwBBAHAAcAAgAD0AIAAiACQARQBOAFYAOgBQAHIAbwBnAHIAYQBtAEQAYQB0AGEAXABjAGgAbwBjAG8AbABhAHQAZQB5AFwAYgBpAG4AIgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBoAG8AYwBvAEEAcABwACAAPQAgAEoAbwBpAG4ALQBQAGEAdABoACAAJABjAGgAbwBjAG8AQQBwAHAAIAAnAGMAaABvAGMAbwAuAGUAeABlACcACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAKAB0AGUAcwB0AC0AcABhAHQAaAAgACQAYwBoAG8AYwBvAEEAcABwACkAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAAkAGMAaABvAGMAbwBBAHAAcAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABUAGgAcgBvAHcAIAAnAEMAbwB1AGwAZAAgAG4AbwB0ACAAbABvAGMAYQB0AGUAIABjAGgAbwBjAG8ALgBlAHgAZQAnAAoAIAAgACAAIAAgACAAIAAgAH0ACgAKACAAIAAgACAAIAAgACAAIAAkAEMAaABvAGMAbwBFAHgAZQBQAGEAdABoACAAPQAgAEcAZQB0AC0AQwBoAG8AYwBvAEUAeABlAFAAYQB0AGgACgAKACAAIAAgACAAIAAgACAAIAAmACIAJABDAGgAbwBjAG8ARQB4AGUAUABhAHQAaAAiACAAJwBpAG4AcwB0AGEAbABsACcAIAAnAGcAaAAnAAoACgAgACAAIAAgACAAIAAgACAAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAANQA="
    $EncodedCommandWinGet = "CgAgACAAIAAgACAAIAAgACAAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBXAGkAbgBHAGUAdABFAHgAZQBQAGEAdABoAHsAIAAgACAACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABbAEMAbQBkAGwAZQB0AEIAaQBuAGQAaQBuAGcAKABTAHUAcABwAG8AcgB0AHMAUwBoAG8AdQBsAGQAUAByAG8AYwBlAHMAcwApAF0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABwAGEAcgBhAG0AKAApAAoACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHcAaQBuAGcAZQB0AEMAbQBkACAAPQAgAEcAZQB0AC0AQwBvAG0AbQBhAG4AZAAgACcAdwBpAG4AZwBlAHQALgBlAHgAZQAnACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABJAGcAbgBvAHIAZQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAoACgAJAB3AGkAbgBnAGUAdABDAG0AZAAgAC0AbgBlACAAJABOAHUAbABsACAAKQAgAC0AQQBuAGQAIAAoAHQAZQBzAHQALQBwAGEAdABoACAALQBQAGEAdABoACAAJwAkACgAJAB3AGkAbgBnAGUAdABDAG0AZAAuAFMAbwB1AHIAYwBlACkAJwAgAC0AUABhAHQAaABUAHkAcABlACAATABlAGEAZgApACkAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAB3AGkAbgBnAGUAdABBAHAAcAAgAD0AIAAkAHcAaQBuAGcAZQB0AEMAbQBkAC4AUwBvAHUAcgBjAGUACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAFYAZQByAGIAbwBzAGUAIAAnAAUnIABGAG8AdQBuAGQAIAB3AGkAbgBnAGUAdAAuAGUAeABlACAAQwBNAEQAIABbACQAdwBpAG4AZwBlAHQAQQBwAHAAXQAnAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABSAGUAdAB1AHIAbgAgACQAdwBpAG4AZwBlAHQAQQBwAHAAIAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAACgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAdwBpAG4AZwBlAHQAQQBwAHAAIAA9ACAAKABSAGUAcwBvAGwAdgBlAC0AUABhAHQAaAAgACIAJABFAE4AVgA6AEEAUABQAEQAQQBUAEEAXAAuAC4AXABMAG8AYwBhAGwAXABNAGkAYwByAG8AcwBvAGYAdABcAFcAaQBuAGQAbwB3AHMAQQBwAHAAcwAiACkALgBQAGEAdABoAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAB3AGkAbgBnAGUAdABBAHAAcAAgAD0AIABKAG8AaQBuAC0AUABhAHQAaAAgACQAdwBpAG4AZwBlAHQAQQBwAHAAIAAnAHcAaQBuAGcAZQB0AC4AZQB4AGUAJwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAoAHQAZQBzAHQALQBwAGEAdABoACAAJAB3AGkAbgBnAGUAdABBAHAAcAApAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJAB3AGkAbgBnAGUAdABBAHAAcAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABUAGgAcgBvAHcAIAAnAEMAbwB1AGwAZAAgAG4AbwB0ACAAbABvAGMAYQB0AGUAIAB3AGkAbgBnAGUAdAAuAGUAeABlACcACgAgACAAIAAgACAAIAAgACAAfQAKAAoAIAAgACAAIAAgACAAIAAgACQAVwBpAG4ARwBlAHQARQB4AGUAUABhAHQAaAAgAD0AIABHAGUAdAAtAFcAaQBuAEcAZQB0AEUAeABlAFAAYQB0AGgACgAKACAAIAAgACAAIAAgACAAIAAmACIAJABXAGkAbgBHAGUAdABFAHgAZQBQAGEAdABoACIAIAAnAGkAbgBzAHQAYQBsAGwAJwAgACcALQAtAGkAZAAnACAAJwBHAGkAdABIAHUAYgAuAGMAbABpACcACgAKACAAIAAgACAAIAAgACAAIABTAHQAYQByAHQALQBTAGwAZQBlAHAAIAA1AA=="
    $EncodedCommand = ''
       
    switch($InstallType)
    {
        'WinGet'    {
                        $EncodedCommand = $EncodedCommandWinGet
                    }

        'Choco'     {
                        $EncodedCommand = $EncodedCommandChoco
                    }

        'Package'   {
                        $EncodedCommand = $EncodedCommandMSI
                    }
        'DelWinGet' {
                        $EncodedCommand = $DelWinGet
                    }
        'DelChoco'  {
                        $EncodedCommand = $DelChoco
                    }
    }


    $PwshExe = (Get-Command 'pwsh.exe').Source
    $ArgumentList = @("-noni", "-nop", "-encodedcommand", "$EncodedCommand")

    $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
    try {
 
        $startProcessParams = @{
            FilePath               = $PwshExe
            ArgumentList           = $ArgumentList
            Verb                   = "RunAs"
            Passthru               = $True
        }
       
        $cmd = Start-Process @startProcessParams
        $cmdExitCode = $cmd.ExitCode

        Write-Verbose -Message "Results cmdExitCode $cmdExitCode cmdId $cmdId cmdName $cmdName"

        $res = [PSCustomObject]@{
                ExitCode           = $cmdExitCode
                ElapsedSeconds     = $stopwatch.Elapsed.Seconds
                ElapsedMs          = $stopwatch.Elapsed.Milliseconds
        }
            
        return $res
    }
    catch {
        Write-Error $_
    }
}
